services:
  pg:
    image: pgvector/pgvector:pg17
    container_name: study_pgvector
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: study_swipe
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
