services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: study-swipe-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      # RDS Database Configuration
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      # OpenAI Configuration
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      # AWS SES Configuration
      AWS_REGION: ${AWS_REGION:-ap-northeast-2}
      SES_ACCESS_KEY: ${SES_ACCESS_KEY}
      SES_SECRET_ACCESS_KEY: ${SES_SECRET_ACCESS_KEY}
      MAIL_FROM: ${MAIL_FROM:-no-reply@study-swipe.com}
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
